services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres_user:postgres_password@db:5432/postgres_db"
      OLLAMA_URL: "http://ollama:11434"  
      QDRANT_URL: "http://qdrant_database:6333"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
      - qdrant_database
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
    - ~/.ollama/models:/root/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: all

  qdrant_database:
    image: qdrant/qdrant:latest
    container_name: qdrant_database
    restart: unless-stopped
    ports:
      - "6333:6333"
    environment:
      QDRANT_CONFIG_PATH: /qdrant/config.yml
    volumes:
      - ./qdrant/config.yml:/qdrant/config.yml
      - ./qdrant_data:/qdrant/storage/
      - ./retrievers:/app/retrieval/

volumes:
  pgdata:
    driver: local
