services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres_user:postgres_password@db:5432/postgres_db"
      OLLAMA_URL: "http://ollama:11434"  
      QDRANT_URL: "http://qdrant_database:6333"
      NEO4J_URL: "bolt://neo4j_database:7687"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
      - qdrant_database
      - neo4j
    volumes:
      - .:/app
    networks:
      - my_network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: always
  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

    
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
    - ~/.ollama/models:/root/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: all
    networks:
      - my_network


  qdrant_database:
    image: qdrant/qdrant:latest
    container_name: qdrant_database
    restart: unless-stopped
    ports:
      - "6333:6333"
    environment:
      QDRANT_CONFIG_PATH: /qdrant/config.yml
    volumes:
      - ./qdrant/config.yml:/qdrant/config.yml
      - ./qdrant_data:/qdrant/storage/
      - ./retrievers:/app/retrieval/
    networks:
      - my_network

  neo4j:
    image: neo4j:latest
    container_name: neo4j_database
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4j_admin
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_connector_http_advertised__address=:7474
      - NEO4J_dbms_default__listen__address=0.0.0.0
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/neo4j/import
      - ./neo4j/plugins:/plugins
    networks:
      - my_network

volumes:
  pgdata:
    driver: local
  neo4j_data:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  neo4j_logs:
    driver: local
networks:
  my_network:
    driver: bridge